name: Build
on: workflow_dispatch
jobs:
  Android:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: protocolbuffers/protobuf
          ref: v3.24.3
          path: protobuf
          submodules: true
      - name: Build
        run: |
          cd protobuf
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE="/usr/local/lib/android/sdk/ndk/23.2.8568313/build/cmake/android.toolchain.cmake" -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_WITH_ZLIB=OFF
          cmake --build .
          cmake --install . --prefix install
      - name: Generate zip
        run: |
            echo ${{ github.sha }} > ./protobuf/build/install/Release.txt
            cd protobuf/build/install
            zip -r ../../../protobuf.android.${{ github.ref_name }}.zip *
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: protobuf.android.${{ github.ref_name }}.zip
